apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: playlist-recommender-apps
  namespace: caiogrossi
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: caiogrossi-project
  
  source:
    repoURL: https://github.com/caiosgrossi/mlops-assignment.git
    targetRevision: HEAD
    path: argocd
  
  destination:
    server: https://kubernetes.default.svc
    namespace: caiogrossi
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
